#dev test config, to be templated
backend:
  port: 18080
  host: backendhost
  schema: http
 
pattern:
  items:
    sparklinks:
      source: <a href="(https)://([\w\d-\.]*):8044/node/containerlogs/(container[_\w\d]*)/([\d\w]*)/([\d\w\?\=\-]*)">
      target: <a href="$1://newurl/jobhistory/logs/$2:8099/$3/$3/$4/$5"  target="_blank">
    version:
      source: <span class="version">([\d\w\-\.]*)</span>
      target: <span class="version">$1 (modified)</span>
    sparkjsons:
      source: \"(stdout|stderr)\"(\s*:\s*)\"(https)://([\w\d-\.]*):8044/node/containerlogs/(container[_\w\d]*)/([\d\w]*)/([\d\w\?\=\-]*)\"
      target: '"$1"$2"$3://newurl/jobhistory/logs/$4:8099/$5/$5/$6/$7" '
 
header:
  request:
    name: X-Proxy
    value: Modifying-Reverse-Proxy
  response:
    name: X-Bnp-Translator
    value: NodeManager-Link-Translator  
 
frontend:
  port: 8080